### PR TITLE
Allow arrow functions in JSX

### PR DESCRIPTION
**Pull request by edvinerikson**
Allow usage of arrow functions in JSX
Currently `<button onClick={() => props.handleClick()}/>` is forbidden.
cc @EnzoMartin @viart

### CODE REVIEW

**Comment by viart** [comment]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md
>A bind call or arrow function in a JSX prop will create a brand new function on every single render. This is bad for performance, as it will result in the garbage collector being invoked way more than is necessary.

**Comment by edvinerikson** [comment]
Their statement isn't completely accurate about that: https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact&code=%0Afunction%20asd(props)%20%7B%0A%20%20%3Cbutton%20onCLick%3D%7B()%20%3D%3E%20%7B%20this.props.onClick()%20%7D%7D%2F%3E%0A%7D%0A

**Comment by viart** [comment]
@edvinerikson in your example `function onCLick() {}` function will be defined (created) each time when `asd()` is called.

Generally, I would not recommend to rely on Babel's internal implementation, since it can be changed potentially in the future, instead I would recommend to define React Component explicitly (JS Class with `someBoundFunc = (...) => {...}`) when the bound function is necessary.

**Comment by edvinerikson** [comment]
I still think arrows should be allowed, since we won't use babel for arrow functions we will be fine anyway.
The use case for this is in a stateless component so I can't use a class.
I created a small perf test
```js
function createBindFunc() {
  function bind() {}
  return bind.bind(this);
}

function createFunc() {
  function wobind() {}
  return wobind;
}

function func() {};

function returnFunc() {
  return func;
}

function run() {
  console.time('bind');
  for (var i = 0; i < 10000; i++) {
    createBindFunc();
  }
  console.timeEnd('bind');
  
  console.time('wobind');
  for (var i = 0; i < 10000; i++) {
    createFunc();
  }
  console.timeEnd('wobind');
  
  console.time('func');
  for (var i = 0; i < 10000; i++) {
    returnFunc();
  }
  console.timeEnd('func');
}
run();

/*
bind: 10.405ms
wobind: 5.324ms
func: 5.085ms
*/

```

**Comment by edvinerikson** [comment]
I think we will be fine by allow this rule. by not allowing it we will definitely annoy our developers since it doesn't really have any perf impact. Not allowing bind is fine but IMO this is too strict.

**Comment by viart** [comment]
>The use case for this is in a stateless component so I can't use a class.
```jsx
myStateLessComponent extends React.Component {
   my = (some) => { 
      return some * some;
   }
   render() {
      return <a onClick={this.some}>a</a>
   }
}
```
Stateless still :) And in this version it doesn't matter how many times the `render` is called, `my()` will be defined only once (per instance).

Re the perf test, in short - it is wrong (tests should be separated, GC (efficiency/times called), memory footprint, passing created func as a reference, etc...).

>we won't use babel for arrow functions
IMO it's pretty optimistic ;) https://kangax.github.io/compat-table/es6/ but who knows :)

**Comment by edvinerikson** [comment]
Still, the performance diff is like 1ms. If it becomes a perf issue we can handle that with a codemod. If disallowing arrow functions is only for perf reasons, IMO it should be allowed.

**Comment by viart** [comment]
@edvinerikson you're talking about 'performance diff', but measuring 'time needed to define the function', side-effect is much wider, try to google why defining of anonymous functions in loops is a very bad thing (in terms of a performance)...

>If it becomes a perf issue we can handle that with a codemod. 
heh, yet-another-tool-which-will-solve-all-your-issues-this-time-for-sure™ :D

P.S. GC (especially the browser's one) is the last thing I would like to play with, if shit happens the way back will be pretty hard (detection the root) and painful (fix).

**Comment by edvinerikson** [comment]
Initialising a class is probably going to be more expensive then executing a function though

**Comment by EnzoMartin** [comment]
The class isn't created at every render though.

https://daveceddia.com/avoid-bind-when-passing-props/

**Pull request closed without merging**
