### PR TITLE
deny unused vars

### PR DESCRIPTION
**Pull request by viart**
http://eslint.org/docs/rules/no-unused-vars

### CODE REVIEW

**Comment by m64253** [comment]
```duplicated mapping key at line 120, column 24```

**Comment by EnzoMartin** [comment]
StatsD in the following examples is a `Class` singleton:

```javascript
const item = new StatsD(config);
return this[singleton];
```

Result:  `error  'item' is defined but never used    no-unused-vars`

```javascript
new StatsD(singletonChecker, config);
return this[singleton];
```

Result: `error  Do not use 'new' for side effects   no-new`

```javascript
StatsD(singletonChecker, config);
return this[singleton];
```

Result: `error  A function with a name starting with an uppercase letter should only be used as a constructor  new-cap`

**Comment by viart** [comment]
@EnzoMartin Not sure I'm following :) let's take it offline.

**Comment by EnzoMartin** [comment]
Shall we get this in?

**Comment by m64253** [comment]
I think so yes.

**Comment by EnzoMartin** [comment]
@viart still want to get this in?

**Comment by edvinerikson** [comment]
I rebased it

**Comment by viart** [comment]
@EnzoMartin yep :P

**Pull request merged**
