### PR TITLE
Allow this keyword in React classes bound methods (using fat arrows)

### PR DESCRIPTION
**Pull request by viart**
To allow code like:
```js
export default class Some extends Component {
  componentDidMount() {
      window.addEventListener('resize', this.handleResize);
  }
  // ...
  handleResize = (evt) => {
    // eslint-disable-next-line no-invalid-this
    this.setState({ width : evt.width, height : evt.height });
  }
  // ...
}
```

### CODE REVIEW

**Comment by edvinerikson** [comment]
react/no-set-state should be 0

**Comment by edvinerikson** [comment]
the title of the PR is kinda misleading

**Comment by viart** [comment]
I believe `react/no-set-state` should be kept, but as a warning.

>the title of the PR is kinda misleading

Which title would you prefer? :)

**Comment by edvinerikson** [comment]
Warnings are annoying as well and we'll likely just disable the rule anyway

**Comment by viart** [comment]
Then I would rather roll it back as it was to motivate for State-less components, AFAICS so far we have 2-3 components which need to be state-full (so we can disable the rule on per-file basis).

**Comment by edvinerikson** [comment]
I don't know. React state is still very powerful and it's sad that we don't use it more.

**Comment by viart** [comment]
I was pretty sure FB was advertising for Stateless components, are they not cool anymoar? :D

**Comment by edvinerikson** [comment]
I am also pretty sure they did not say that setState is bad :P use stateless components when you don't need state. however there is still use-cases for setState

**Comment by viart** [comment]
>however there is still use-cases for setState

sure thing :P this why we have 2-3 those statefull components.

**Pull request merged**
