### PR TITLE
Allow variable shadowing

### PR DESCRIPTION
**Pull request by EnzoMartin**
Use reactions to vote, 👍 for yes, 👎 for no

### CODE REVIEW

**Comment by m64253** [comment]
>disallow variable declarations from shadowing variables declared in the outer scope

http://eslint.org/docs/rules/no-shadow

**Comment by m64253** [comment]
Do you have a use case for when this is a bad thing?

**Comment by EnzoMartin** [comment]
There's no case where this rule is a problem, it's just a convenience factor with callbacks, mostly targeting using the `err` variable in scopes

Possibly could allow specific ones, like `err`, to compromise if you feel strongly about this rule

**Comment by EnzoMartin** [comment]
I do feel that scope shadowing is a very important concept for all developers to understand in JS, so having a rule that safeguards you against that is like protecting someone from diving below the surface of water.

**Comment by beckend** [comment]
They should understand, but in a medium to long file godamn it's confusing to read.

**Comment by EnzoMartin** [comment]
Alright, what if only `err` was allowed to be shadowed?

**Comment by m64253** [comment]
>Alright, what if only err was allowed to be shadowed?

Why it might even be the most critical thing not to shadow!?

I think believe that having to disable the no-shadow rule is more of symptom of needing to do refactoring.

**Comment by EnzoMartin** [comment]
Fair enough

**Pull request closed without merging**
