### PR TITLE
DELETE rule key-spacing, dont crave alignment

### PR DESCRIPTION
**Pull request by rosven**
Add reactions to vote:
- 👍  for yes
- 👎  for no
- 😕 for don't care
- 🎉 for I hate Robin, (sincerely - @EnzoMartin)

### CODE REVIEW

**Comment by edvinerikson** [comment]
don't care means remove rule?

**Comment by rosven** [comment]
@edvinerikson Well the voting was obviously invented by @EnzoMartin so I guess don't care is as useless as a blank vote always is. It has no power.

**Comment by EnzoMartin** [comment]
Don't care means yes or no doesn't matter

**Comment by m64253** [comment]
Dual meaning, alignment != spacing. I agree with alignment not spacing.

**Comment by EnzoMartin** [comment]
Need to bump version before merge

**Pull request merged**
